### ISSUE TITLE
Do you want an MCU configuration Dialog?

### ISSUE THREAD

**Issue by snikeguo** [WiseLord/qtcreator-wizards#1]
such as STM32CUBEMX：
![image](https://cloud.githubusercontent.com/assets/20830435/26626862/28028e7e-462b-11e7-9708-95e8a8426f46.png)

SPC5Studio（ No ARM kernel. this is PowerPC kernel）:
![image](https://cloud.githubusercontent.com/assets/20830435/26627114/e0b8ceec-462b-11e7-9dd7-1022b2ca1599.png)

of course. if these 51、AVR、MSP430 have a configuration  dialog,then Developers can quickly develop projects.
Do you want an MCU configuration Dialog?

**Comment by snikeguo** [comment]
this config tools name is "MCU config Dialog". it contain all MCUs.(51、AVR 、430、ARM、PowerPC)
The tool can generate the json file, and then the parser driver for each chip can identify the json configuration file and convert the json configuration file to the initialization code.
Each MCU configuration interface is a plug-in.

**Comment by WiseLord** [comment]
Of course, it would be nice to have something similar to this. But I'm not very familiar with STM32 family, those configs I have here are just for my own needs, so I'm not sure I could work on support of other MCUs.

**Comment by snikeguo** [comment]
You know, no matter what kind of MCU, it can be in accordance with the module partition.Such as For any a MCU clock tree, is merely  a multi-input multi-output system.
I am developing this open source project, now the question is: because I use C#/ WPF development, chip controls will not make, you know, the chip of east, south, west and north four directions have pins, I will not put the pin in the south, west, north three directions in this.

I'm sorry, I am from China, not familiar with English
